# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__, np.__config__

('1.13.3',
 <module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>)

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
x = np.zeros(10)
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
x.nbytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
x = np.zeros(10)
x[4] = 1
x

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [7]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
m = np.arange(0,9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [14]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
m = np.random.randint(100,size=(3,3,3))
m

array([[[71, 50,  1],
        [65,  7, 54],
        [65, 20, 60]],

       [[44,  4,  4],
        [50, 53,  7],
        [45, 55, 58]],

       [[66, 41,  3],
        [22, 11, 61],
        [80, 20, 71]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
m = np.random.randint(500,size=(10,10))
print(m)
m.max(), m.min()

[[211 110 290  12  55 271  85  24 426  75]
 [395 241 112  95 246 109 473 230  80 181]
 [405 205 173  66 183 369  11 116 337 392]
 [317 358  33 122  73 276 461 199 412 284]
 [441 440  95 372 255  78 276 319 127  60]
 [124 340 157 365 226 161 356 418 329 412]
 [280 303 116 490 485 450 479  50 489 226]
 [353  73 341 101 142 246  61   2 341 237]
 [ 90  57 173 170  92 346  46  24 195 326]
 [205 152 216 428 128 427  58 476 170 102]]


(490, 2)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
x = np.random.randint(100, size=30)
print(x)
x.mean()

[72 53 85 57 95 90 91 44  0 95 32 81 40 46 96 87 59 45 99 42 14 15 41 45 92
 15 51  5 17 22]


54.200000000000003

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [6]:
m = np.ones((10,10))
m[1:-1,1:-1] = 0
m

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [10]:
np.pad(m, pad_width = 1, mode = 'constant', constant_values = 0)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [11]:
0 * np.nan, np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, 0.3 == 3 * 0.1

(nan, False, False, nan, False)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [12]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
m = np.zeros((8,8),dtype = int)
m[1::2,::2] = 1
m[::2,1::2] = 1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [24]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
a = np.array([[0,1],[1,0]])
np.tile(a, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
A = np.random.random((5,5))
Amax, Amin = A.max(), A.min()
A = (A - Amin)/(Amax - Amin)
print(A)

[[ 0.25589194  0.18971441  0.86720293  0.11973032  0.56845774]
 [ 0.15876198  0.89183698  0.7846927   0.82712495  0.63047372]
 [ 0.61126033  0.91497385  0.38782394  0.76687001  0.75345338]
 [ 0.37157233  0.          0.98911141  1.          0.62939531]
 [ 0.05037899  0.8486808   0.93777514  0.79364163  0.17940358]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [29]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [31]:
A = np.random.randint(10, size = (5,3))
B = np.random.randint(10, size = (3,2))
print(A)
print(B)
np.dot(A,B)

[[7 5 1]
 [2 2 0]
 [1 7 6]
 [9 2 8]
 [5 6 6]]
[[3 5]
 [5 9]
 [2 1]]


array([[48, 81],
       [16, 28],
       [50, 74],
       [53, 71],
       [57, 85]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [34]:
x = np.random.randint(10,size = 10)
x[(x>=3)&(x<=8)]*=-1
x

array([-5,  2,  1,  1, -8, -7, -5,  2, -5, -4])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))
np.sum(range(5),-1)

9


10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [71]:
#ВСЕ КРОМЕ ПОСЛЕДНЕГО

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [90]:
np.array(0) / np.array(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [91]:
np.array(0) // np.array(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [92]:
np.array([np.nan]).astype(int).astype(float)

array([ -2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [94]:
Z = np.random.uniform(-10,10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 5.23797684 -9.62717512 -5.16612103  7.18738882  1.28355167  1.7954982
  3.6559072   8.36847914 -6.49399245  6.0783514 ]
[  6. -10.  -6.   8.   2.   2.   4.   9.  -7.   7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [96]:
x = np.random.randint(0,10,10)
print('x= ', x)
y = np.random.randint(0,10,10)
print('y= ', y)
print('intersection= ', np.intersect1d(x,y))

x=  [9 6 2 7 6 9 8 4 7 4]
y=  [1 7 8 4 9 0 1 9 5 1]
intersection=  [4 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [100]:
with np.errstate(divide='ignore'):
    x = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [106]:
print(np.sqrt(-1), np.emath.sqrt(-1))

nan 1j


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [109]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')  
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
today, yesterday, tomorrow

(numpy.datetime64('2018-05-19'),
 numpy.datetime64('2018-05-18'),
 numpy.datetime64('2018-05-20'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [110]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [111]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [13]:
M = np.random.uniform(-10,10,15)
print(M)
print(M.astype(int))
print(np.trunc(M))
print(np.copysign(np.floor(np.abs(M)), M))
print(np.copysign(np.floor(np.abs(M)), M))
print(np.copysign(np.ceil(np.abs(M))-1, M))
print(np.copysign(np.abs(M)-np.abs(M)%1, M))

[ 9.58151013 -6.17102949 -6.61644164  0.02374474  1.17305723 -1.87679497
 -4.45009481 -6.20861383  4.54225367 -2.98899434  7.20986881 -7.69486783
 -1.4687218   5.20300441 -8.86006184]
[ 9 -6 -6  0  1 -1 -4 -6  4 -2  7 -7 -1  5 -8]
[ 9. -6. -6.  0.  1. -1. -4. -6.  4. -2.  7. -7. -1.  5. -8.]
[ 9. -6. -6.  0.  1. -1. -4. -6.  4. -2.  7. -7. -1.  5. -8.]
[ 9. -6. -6.  0.  1. -1. -4. -6.  4. -2.  7. -7. -1.  5. -8.]
[ 9. -6. -6.  0.  1. -1. -4. -6.  4. -2.  7. -7. -1.  5. -8.]
[ 9. -6. -6.  0.  1. -1. -4. -6.  4. -2.  7. -7. -1.  5. -8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [15]:
np.zeros((5,5)) + np.arange(5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [18]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [23]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [33]:
np.sort(np.random.random(10))

array([ 0.33040771,  0.40827582,  0.4884826 ,  0.53408125,  0.56680238,
        0.58274398,  0.63615928,  0.80989431,  0.9500932 ,  0.98317248])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [38]:
Z = np.arange(100)

In [39]:
%timeit np.add.reduce(Z)

3.38 µs ± 245 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
%timeit(sum(Z))

16.1 µs ± 72.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [43]:
A = np.random.randint(10, size = 5)
B = np.random.randint(10, size = 5)
print(A)
print(B)
np.array_equal(A,B)

[4 8 6 2 2]
[3 4 3 2 4]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
x = np.random.randint(10, size = 5)
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [54]:
XY = np.random.uniform(0,10,(10,2))
print(XY)
PR = np.empty(XY.shape)
PR[:,0]= np.sqrt(XY[:,0]**2+XY[:,1]**2)
PR[:,1] = np.arctan2(XY[:,1],XY[:,0])
print(PR)

[[ 4.11856238  8.60101494]
 [ 9.31099418  9.57444612]
 [ 7.94740841  2.05560933]
 [ 1.5765706   5.36659469]
 [ 3.88373091  0.79348826]
 [ 8.82290485  2.01527892]
 [ 9.6632982   6.88966754]
 [ 8.57441118  1.44637146]
 [ 2.28357321  1.91552097]
 [ 0.60525344  1.40512479]]
[[  9.53624737   1.12421461]
 [ 13.3553222    0.79934726]
 [  8.20894818   0.25310456]
 [  5.59338121   1.28506041]
 [  3.96396133   0.20153713]
 [  9.05013807   0.22456197]
 [ 11.86789159   0.6193795 ]
 [  8.69554584   0.16711147]
 [  2.98059175   0.69797121]
 [  1.52993706   1.16406792]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [55]:
x = np.random.randint(10, size = 10)
print(x)
x[x.argmax()] = 0
print(x)

[2 8 4 9 2 1 6 4 5 4]
[2 8 4 0 2 1 6 4 5 4]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [59]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


(5, 5)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [4]:
X = np.random.randint(10, size = 5)
Y = np.random.randint(10, 20,size = 4)
print (X)
print (Y)
C = 1/np.subtract.outer(X,Y)
print(C)

[9 0 2 4 2]
[16 14 19 14]
[[-0.14285714 -0.2        -0.1        -0.2       ]
 [-0.0625     -0.07142857 -0.05263158 -0.07142857]
 [-0.07142857 -0.08333333 -0.05882353 -0.08333333]
 [-0.08333333 -0.1        -0.06666667 -0.1       ]
 [-0.07142857 -0.08333333 -0.05882353 -0.08333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [5]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


#### 49. How to print all the values of an array? (★★☆)

In [8]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,14))
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [15]:
x = np.random.randint(100,size = 10)
print(x)
v = 14
np.abs(x-v)
ind = np.argmin(np.abs(x-v))
print(x[ind])

[82 37  0 24 51 61 48 41 78 44]
24


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [16]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [23]:
Z = np.random.randint(5,size = (10,2))
print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[1 4]
 [0 1]
 [4 1]
 [4 3]
 [4 3]
 [1 0]
 [3 0]
 [0 2]
 [3 3]
 [4 3]]
[[ 0.     3.162  4.243  3.162  3.162  4.     4.472  2.236  2.236  3.162]
 [ 3.162  0.     4.     4.472  4.472  1.414  3.162  1.     3.606  4.472]
 [ 4.243  4.     0.     2.     2.     3.162  1.414  4.123  2.236  2.   ]
 [ 3.162  4.472  2.     0.     0.     4.243  3.162  4.123  1.     0.   ]
 [ 3.162  4.472  2.     0.     0.     4.243  3.162  4.123  1.     0.   ]
 [ 4.     1.414  3.162  4.243  4.243  0.     2.     2.236  3.606  4.243]
 [ 4.472  3.162  1.414  3.162  3.162  2.     0.     3.606  3.     3.162]
 [ 2.236  1.     4.123  4.123  4.123  2.236  3.606  0.     3.162  4.123]
 [ 2.236  3.606  2.236  1.     1.     3.606  3.     3.162  0.     1.   ]
 [ 3.162  4.472  2.     0.     0.     4.243  3.162  4.123  1.     0.   ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [25]:
Z = np.arange(10, dtype=np.float32)
print(Z)
Z = Z.astype(np.int32, copy=False)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [62]:
from io import StringIO

#Fake file
s = """1, 2, 3, 4, 5\n
       6,  ,  , 7, 8\n
        ,  , 9,10,11\n"""
Z = np.fromstring(s, sep=",", dtype=np.int)
print(Z)

[1 2 3 4 5]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [64]:
Z = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [70]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[ 0.368  0.448  0.52   0.574  0.603  0.603  0.574  0.52   0.448  0.368]
 [ 0.448  0.546  0.633  0.699  0.734  0.734  0.699  0.633  0.546  0.448]
 [ 0.52   0.633  0.734  0.811  0.852  0.852  0.811  0.734  0.633  0.52 ]
 [ 0.574  0.699  0.811  0.895  0.94   0.94   0.895  0.811  0.699  0.574]
 [ 0.603  0.734  0.852  0.94   0.988  0.988  0.94   0.852  0.734  0.603]
 [ 0.603  0.734  0.852  0.94   0.988  0.988  0.94   0.852  0.734  0.603]
 [ 0.574  0.699  0.811  0.895  0.94   0.94   0.895  0.811  0.699  0.574]
 [ 0.52   0.633  0.734  0.811  0.852  0.852  0.811  0.734  0.633  0.52 ]
 [ 0.448  0.546  0.633  0.699  0.734  0.734  0.699  0.633  0.546  0.448]
 [ 0.368  0.448  0.52   0.574  0.603  0.603  0.574  0.52   0.448  0.368]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [71]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [77]:
M = np.random.randint(10, size = (4,5))
print(M)
mean = M.mean(axis = 1,keepdims=True)
print(mean)
M - mean

[[2 5 7 4 5]
 [7 7 3 8 6]
 [6 8 0 5 0]
 [1 6 4 4 7]]
[[ 4.6]
 [ 6.2]
 [ 3.8]
 [ 4.4]]


array([[-2.6,  0.4,  2.4, -0.6,  0.4],
       [ 0.8,  0.8, -3.2,  1.8, -0.2],
       [ 2.2,  4.2, -3.8,  1.2, -3.8],
       [-3.4,  1.6, -0.4, -0.4,  2.6]])

#### 59. How to sort an array by the nth column? (★★☆)

In [78]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 0 7]
 [3 7 9]
 [1 2 4]]
[[1 0 7]
 [1 2 4]
 [3 7 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [82]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[1 2 0 0 1 1 1 1 2 2]
 [0 2 1 0 2 1 2 2 1 2]
 [0 1 0 0 1 2 0 1 1 0]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [2]:
x = np.random.randint(100,size = 10)
print(x)
v = 14
np.abs(x-v)
ind = np.argmin(np.abs(x-v))
print(x[ind])

[63 65 42 20 80 72 53  3 77 95]
20


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [6]:
A = np.arange(3).reshape(3,1)
print(A)
B = np.arange(3).reshape(1,3)
print(B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [7]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)
Z[5]

range_10


5

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(I)
np.add.at(Z, I, 1)
print(Z)

[7 1 8 1 8 5 8 7 2 7 7 0 6 8 0 4 0 1 0 3]
[ 5.  4.  2.  2.  2.  2.  2.  5.  5.  1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [13]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [16]:
A = np.random.randint(0,10,(3,4,3,4))
s = A.sum(axis=(-2,-1))
print(s)

[[60 50 46 51]
 [43 40 50 59]
 [64 42 61 69]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [46]:
D = np.random.uniform(0,1,10)
print(D)
S = np.random.randint(0,10,10)
print(S)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[ 0.533  0.804  0.664  0.734  0.78   0.311  0.054  0.689  0.556  0.582]
[9 1 4 5 9 3 4 1 3 0]
0    0.581742
1    0.746735
3    0.433592
4    0.359292
5    0.734385
9    0.656312
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [47]:
A = np.random.randint(10, size = (3,3))
print(A)
B = np.random.randint(10, size = (3,3))
print(B)
C = np.dot(A,B)
print(C)
np.diag(C)

[[7 0 2]
 [3 9 3]
 [4 7 7]]
[[6 5 7]
 [0 9 0]
 [6 3 6]]
[[ 54  41  61]
 [ 36 105  39]
 [ 66 104  70]]


array([ 54, 105,  70])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [51]:
x = np.array([1, 2, 3, 4, 5])
nx = 3
x0 = np.zeros(len(x) + (len(x)-1)*nx)
x0[::nx+1] = x
print(x0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [52]:
A = np.arange(1, 10).reshape(3,3)
A[[0,1]] = A[[1,0]]
A

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [57]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [17]:
Z = np.arange(10)
print(Z)
np.lib.stride_tricks.as_strided(Z, shape = (8, 3), strides = (4,4))

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [3]:
Z = np.random.randint(0,2,10)
print(Z)
np.logical_not(Z, out=Z)
print(Z)

Z = np.random.uniform(-1.0,1.0,10)
print(Z)
np.negative(Z, out=Z)
print(Z)

[1 0 0 0 0 1 0 0 1 0]
[0 1 1 1 1 0 1 1 0 1]
[ 0.371  0.96   0.426  0.057 -0.576 -0.923 -0.777  0.584 -0.244  0.309]
[-0.371 -0.96  -0.426 -0.057  0.576  0.923  0.777 -0.584  0.244 -0.309]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [15]:
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [11]:
M = np.random.randint(10, size = (3, 3))
print(M)
np.linalg.matrix_rank(M)

[[0 1 3]
 [9 7 1]
 [9 6 9]]


3

#### 83. How to find the most frequent value in an array?

In [4]:
Z = np.random.randint(0,4,10)
print(Z)
print(np.bincount(Z).argmax())

[2 3 3 1 2 2 2 1 2 3]
2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [26]:
M = np.random.randint(0,10,(10,10))
print(M)
C = np.lib.stride_tricks.as_strided(M, shape=(8,8,3,3), strides = M.strides*2)
print(C)

[[6 2 3 1 5 0 9 9 1 8]
 [1 7 6 6 6 4 5 7 4 8]
 [4 8 2 8 2 7 0 0 5 3]
 [2 9 9 2 6 3 1 8 8 2]
 [1 1 5 3 3 2 9 8 7 4]
 [0 0 3 4 5 8 3 2 0 5]
 [7 9 4 9 1 4 1 1 3 5]
 [7 7 5 4 5 9 6 5 4 6]
 [2 6 0 4 3 0 7 9 0 8]
 [4 6 9 9 7 6 0 6 6 5]]
[[[[6 2 3]
   [1 7 6]
   [4 8 2]]

  [[2 3 1]
   [7 6 6]
   [8 2 8]]

  [[3 1 5]
   [6 6 6]
   [2 8 2]]

  [[1 5 0]
   [6 6 4]
   [8 2 7]]

  [[5 0 9]
   [6 4 5]
   [2 7 0]]

  [[0 9 9]
   [4 5 7]
   [7 0 0]]

  [[9 9 1]
   [5 7 4]
   [0 0 5]]

  [[9 1 8]
   [7 4 8]
   [0 5 3]]]


 [[[1 7 6]
   [4 8 2]
   [2 9 9]]

  [[7 6 6]
   [8 2 8]
   [9 9 2]]

  [[6 6 6]
   [2 8 2]
   [9 2 6]]

  [[6 6 4]
   [8 2 7]
   [2 6 3]]

  [[6 4 5]
   [2 7 0]
   [6 3 1]]

  [[4 5 7]
   [7 0 0]
   [3 1 8]]

  [[5 7 4]
   [0 0 5]
   [1 8 8]]

  [[7 4 8]
   [0 5 3]
   [8 8 2]]]


 [[[4 8 2]
   [2 9 9]
   [1 1 5]]

  [[8 2 8]
   [9 9 2]
   [1 5 3]]

  [[2 8 2]
   [9 2 6]
   [5 3 3]]

  [[8 2 7]
   [2 6 3]
   [3 3 2]]

  [[2 7 0]
   [6 3 1]
   [3 2 9]]

  [[7 0 0]
   [3 1 8]
   [2 9 

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [6]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  6  1  9  9]
 [ 6  6 10 13  3]
 [ 1 10  3 42  9]
 [ 9 13 42  9  7]
 [ 9  3  9  7  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [16]:
x = np.random.randint(10, size = 15)
print(x)
x[np.argsort(x)[-5:]]

[2 6 5 1 0 4 5 9 0 8 0 2 6 1 6]


array([6, 6, 6, 8, 9])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [29]:
I = np.array([8, 1, 2, 7, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [17]:
M = np.random.randint(0,2,(8,3)) 
print(M)
np.unique(M, axis = 0)

[[1 0 0]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [1 1 0]
 [1 1 0]
 [1 0 1]
 [0 0 1]]


array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)